# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ProjectVerkeerGent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectVerkeerGent

  target 'ProjectVerkeerGentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectVerkeerGentUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'SwiftyJSON'
pod 'Alamofire', '~> 4.0'
pod 'RealmSwift'

end
